mattrubin/OneTimePassword

- .travis.yml
Update the Travis CI configuration file to build the project for iOS 8.4, with Xcode 6.4, using xcodebuild and xcpretty.
> Travis Configuration

- .gitignore
- .travis.yml
- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePassword.xcodeproj/xcshareddata/xcschemes/OneTimePassword.xcscheme
- OneTimePassword.xcodeproj/xcshareddata/xcschemes/OneTimePasswordLegacy.xcscheme
- OneTimePassword/Generator.swift
- OneTimePassword/GeneratorFunctions.swift
- OneTimePassword/Info.plist
- OneTimePassword/Keychain.swift
- OneTimePassword/Token.URLSerializer.swift
- OneTimePassword/Token.swift
- OneTimePassword/TokenPersistence.swift
- OneTimePasswordLegacy/Info.plist
- OneTimePasswordLegacy/OTPToken.swift
- OneTimePasswordLegacyTests/Info.plist
- OneTimePasswordTests/GeneratorTests.swift
- OneTimePasswordTests/Info.plist
- OneTimePasswordTests/TokenSerializationTests.swift
- Updated source for Swift 2 and updated APIs
- Updated `.gitignore` to ignore Xcode 7's `.xcscmblueprint` files
- Updated Travis configuration to build with Xcode 7 and iOS 9
- Automated update of project file, schemes, and info plists for Xcode 7
> Xcode 7 & Swift 2

- Cartfile
- Cartfile.resolved
- OneTimePassword.xcodeproj/project.pbxproj
Update `xcconfigs` and clean up build settings
> Build Settings

- OneTimePassword/Generator.swift
- OneTimePassword/Token.swift
Improves the documentation comments on `Generator` and `Token`.
> Better Documentation

- OneTimePasswordLegacy/OTPToken.swift
Publicize methods for converting between `Token` and `OTPToken`
> Conversion

- OneTimePassword/Token.URLSerializer.swift
- OneTimePassword/TokenPersistence.swift
- OneTimePassword/TokenSerializer.swift
- OneTimePasswordLegacy/OTPToken.swift
- OneTimePasswordTests/TokenSerializationTests.swift
Change `Token.URLSerializer` to actually serialize to `URL`, not `String`.
> URL Serialization

- .hound.yml
- .swiftlint.yml
- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePassword/Generator.swift
- OneTimePassword/GeneratorFunctions.swift
- OneTimePassword/Keychain.swift
- OneTimePassword/Token.URLSerializer.swift
- OneTimePassword/Token.swift
- OneTimePassword/TokenPersistence.swift
- OneTimePasswordLegacy/OTPToken.swift
- OneTimePasswordLegacyTests/OTPTokenSerializationTests.m
- OneTimePasswordTests/GeneratorTests.swift
Configure the Xcode project to run [SwiftLint](https://github.com/realm/SwiftLint) on every build, and configure [Hound](https://houndci.com) to sun the linter on pull requests.
Many small pieces of code have been refactored to appease the linter. Some SwiftLint rules have been disabled because satisfying them will require more extensive refactoring.
> SwiftLint and Hound CI

- .hound.yml
- OneTimePassword/Generator.swift
- OneTimePassword/Token.swift
- OneTimePasswordLegacy/OTPToken.swift
- OneTimePasswordTests/GeneratorTests.swift
Move the time-based `currentPassword` property from `Generator` to `Token`.
> Password property

- .hound.yml
- .swiftlint.yml
- .travis.yml
- Cartfile
- Cartfile.resolved
- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePassword.xcodeproj/xcshareddata/xcschemes/OneTimePassword.xcscheme
- OneTimePassword.xcodeproj/xcshareddata/xcschemes/OneTimePasswordLegacy.xcscheme
- Upgrade project file for Xcode 7.1
- Add references to tool configuration files to the Xcode project
- Update `xcconfigs`
> Project Improvements

- OneTimePassword/TokenPersistence.swift
Implement Equatable for Token.KeychainItem
> KeychainItem equality

- OneTimePassword/Generator.swift
- OneTimePassword/Token.swift
- OneTimePasswordLegacyTests/OTPToken.swift
> API cleanup

- .travis.yml
- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePassword/Keychain.swift
Upgrade Travis to build with Xcode 7.1 and the iOS 9.1 SDK, and configure a build matrix to run the tests on multiple devices and iOS versions.
> Travis Build Matrix

- OneTimePassword.podspec
- OneTimePassword/Info.plist
Bump the project version to 1.1.1 and update the Podspec to reflect the new requirements.
> Podspec for 1.1.1

- OneTimePassword.xcodeproj/project.pbxproj
Update xcodeproj version and specify project defaults for indentation and prefixing.
> Project defaults

- .swiftlint.yml
- OneTimePassword/Keychain.swift
- OneTimePassword/PersistentToken.swift
- OneTimePassword/Token+URL.swift
- OneTimePasswordLegacyTests/OTPToken.swift
- Selectively enable and disable new SwiftLint rules.
- Add missing documentation comments.
> Add missing documentation comments

- CONDUCT.md
- CONTRIBUTING.md
- OneTimePassword.xcodeproj/project.pbxproj
- README.md
Add contributing guidelines and a code of conduct.
> Add Contributing Guidelines

- .gitmodules
- Cartfile
- Cartfile.resolved
- CommonCrypto/appletvos/module.modulemap
- CommonCrypto/appletvsimulator/module.modulemap
- CommonCrypto/iphoneos/module.modulemap
- CommonCrypto/iphonesimulator/module.modulemap
- CommonCrypto/macosx/module.modulemap
- CommonCrypto/watchos/module.modulemap
- CommonCrypto/watchsimulator/module.modulemap
- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePassword.xcworkspace/contents.xcworkspacedata
Remove external `Crypto` dependency, and import custom modulemap files to link to `CommonCrypto`.
> CommonCrypto

- Cartfile.private
- OneTimePassword.xcodeproj/project.pbxproj
Make `jspahrsummers/xcconfigs` a private dependency.
> Private Dependencies

- .swiftlint.yml
- LICENSE.md
- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePassword/Generator.swift
- OneTimePassword/OneTimePassword.h
- OneTimePassword/Token.swift
- OneTimePasswordLegacyTests/OTPToken.swift
- Standardize two-space indentation in YAML files.
- Clean up and fix assorted doc comments.
- Update copyright dates.
> Assorted Cleanup

- OneTimePassword.podspec
- OneTimePassword.xcodeproj/project.pbxproj
- Include podspec in the project in the Tools category
- Correctly capitalize URLs in the podspec
> Podspec improvements 

- README.md
Add installation and usage instructions to the README file.
> Installation and Usage Instructions

- CommonCrypto/README.md
Add a README file to the CommonCrypto folder to explain the custom modulemaps.
> CommonCrypto README

- .travis.yml
- OneTimePassword/Generator.swift
- OneTimePasswordTests/TokenTests.swift
Add `testCurrentPassword()` and `testUpdatedTokens()` for full test coverage on `Token`. Also, upgrade the Travis build configuration to use Xcode 7.2 and iOS 9.2.
> Complete Token Tests

- CHANGELOG.md
Add changeling entries for all of the PRs which have been merged since 2.0.
> Update Changelog for 2.0.1

- CHANGELOG.md
- Configuration/CommonCrypto.xcconfig
- Configuration/OneTimePassword-iOS.xcconfig
- Configuration/OneTimePassword-watchOS.xcconfig
- Configuration/OneTimePassword.xcconfig
- Configuration/OneTimePasswordTests-iOS.xcconfig
- Configuration/OneTimePasswordTests.xcconfig
- OneTimePassword.xcodeproj/project.pbxproj
Move common build settings into shared `xcconfig` files.
> Add configuration files

- CHANGELOG.md
- OneTimePassword.podspec
- Sources/Info.plist
Update the changelog and framework version numbers for 2.1.
> Update changelog and version numbers

- .swiftlint.yml
- OneTimePasswordLegacyTests/OTPToken.swift
- Sources/Generator.swift
- Sources/Keychain.swift
- Sources/Token+URL.swift
- Tests/KeychainTests.swift
- Tests/TokenSerializationTests.swift
Update the SwiftLint configuration for SwiftLint 0.15, enabling many new rules and disabling some others.
> SwiftLint 0.15

- CHANGELOG.md
- OneTimePassword.podspec
- Sources/Info.plist
Bump the version number and update the changelog for version 2.1.1.
> Prepare version 2.1.1

- .swiftlint.yml
- .travis.yml
- CHANGELOG.md
- Configuration/OneTimePasswordTestApp.xcconfig
- Configuration/OneTimePasswordTests-iOS.xcconfig
- OneTimePassword.podspec
- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePasswordLegacyTests/OTPToken.swift
- Sources/Generator.swift
- Sources/Info.plist
- Sources/Keychain.swift
- Sources/Token+URL.swift
- Tests/App/AppDelegate.swift
- Tests/App/Info.plist
- Tests/App/Launch Screen.storyboard
- Tests/KeychainTests.swift
- Tests/TokenSerializationTests.swift
Before merging:
After merging:
> Release OneTimePassword 2.1.1

- README.md
Update the usage instructions and code examples for the Swift 3 API.
> Update the README for Swift 3

- CHANGELOG.md
- CONTRIBUTING.md
Also, fix a broken link in the Contributing file.
> Update the changelog for OneTimePassword 3.0
