- .gitmodules
- Cartfile
- Cartfile.resolved
- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePassword.xcworkspace/contents.xcworkspacedata
- OneTimePassword/GeneratorFunctions.swift
- OneTimePassword/OneTimePassword-Bridging-Header.h
- OneTimePassword/OneTimePassword.h
- Add an umbrella header (to quiet Xcode's warning)
- Remove the umbrella header (which isn't allowed in frameworks)
- Add a framework wrapper for CommonCrypto (so it can be accessed from Swift).
> CommonCrypto wrapper

- OneTimePassword/GeneratorFunctions.swift
- Add helper function for padding the password string without looping.
- Replace `NSMutableData` with an `UnsafeMutablePointer<UInt8>` (The `NSMutableData` was already being used in an "unsafe" way).
- Use `sizeof(UInt64)` instead of hard-coding byte count.
> Refactor password generation

- OneTimePassword/Generator.swift
- OneTimePassword/GeneratorFunctions.swift
- OneTimePassword/Token.URLSerializer.swift
- OneTimePasswordLegacy/OTPToken.swift
- OneTimePasswordTests/GeneratorTests.swift
Remove validation on `Generator` and replace it with safety checks at generation time. The acceptable values for these checks are defined by what values the algorithm can handle without an error, rather than arbitrarily constraining the `Generator` properties.
The old validation rules are moved to the legacy `OTPToken`.
> Generator Error Handling

- OneTimePassword/Generator.swift
- OneTimePassword/Token.URLSerializer.swift
- OneTimePasswordLegacy/OTPToken.swift
- OneTimePasswordTests/EquatableTests.swift
- OneTimePasswordTests/GeneratorTests.swift
- OneTimePasswordTests/TokenTests.swift
The `Generator` shouldn't have default values for its `algorithm` or `digits` properties; it should always be initialized with the full set of parameters for password generation. The `URLSerializer` *does* need default values, as specified by the [URI format](https://github.com/google/google-authenticator/wiki/Key-Uri-Format).
This pull request removes the defaults from the generator, moves them to the serializer, and gives `OTPToken` its own legacy defaults. The tests are updated accordingly.
> Remove Generator Defaults

- OneTimePassword.xcodeproj/project.pbxproj
Pick an automatic code signing identity when building for iOS.
> Fix iOS Code Signing

- .hound.yml
- OneTimePassword.xcodeproj/project.pbxproj
- Configure Hound to use the same configuration as local linting.
- Run the linter after the compiler. This prevents style errors from masking compilation errors.
> Improved Linter Configuration

- OneTimePassword/Generator.swift
- OneTimePassword/GeneratorFunctions.swift
- OneTimePassword/Token.URLSerializer.swift
- OneTimePassword/Token.swift
- OneTimePasswordLegacy/Conversion.swift
- OneTimePasswordLegacy/OTPToken.swift
- OneTimePasswordLegacyTests/OTPTokenSerializationTests.m
- OneTimePasswordTests/EquatableTests.swift
- OneTimePasswordTests/GeneratorTests.swift
- OneTimePasswordTests/TokenSerializationTests.swift
- OneTimePasswordTests/TokenTests.swift
Convert `Generator.init` to a failable initializer that validates the generation parameters. By doing so, the immutable `Generator` becomes a type where *invalid states are impossible* to initialize. If a `Generator` exists, it can produce a password.
Also:
- Tighten the range of acceptable password lengths
- Loosen the restrictions on valid timer periods
> Validate Generator on Initialization

- OneTimePassword/Keychain.swift
- OneTimePasswordLegacy/OTPToken.swift
- OneTimePasswordTests/TokenPersistenceTests.swift
When a `Sec*` keychain method returns an error result code, the wrapping keychain methods will now throw an error rather than just returning nil. This helps clarify the difference between methods returning no value as a valid result, and methods which throw errors in exceptional cases.
> Keychain errors

- OneTimePassword/Keychain.swift
- OneTimePassword/PersistentToken.swift
- OneTimePasswordTests/TokenPersistenceTests.swift
Return a `Set`, rather than an `Array`, from `allPersistentTokens()`
> Persistent Token Set

- OneTimePassword/Keychain.swift
allPersistentTokens() returns a set, not an array.
> Documentation comment fix

- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePasswordTests/KeychainTests.swift
- OneTimePasswordTests/TokenPersistenceTests.swift
Cleaned up (and renamed) the keychain tests to better match the new Keychain API.
> Keychain Tests

- README.md
Improve formatting of code blocks in the README file. The extra line breaks and code style specifier help non-GitHub parsers translate the markdown as intended.
> README code blocks

- README.md
Fix the `passwordAtTime(_:)` usage example in the README.
> README Usage Fix

- OneTimePassword.xcodeproj/project.pbxproj
- Sources/Crypto.swift
- Sources/Generator.swift
Isolate the CommonCrypto dependency inside a custom wrapper function, in preparation for replacing it with a different HMAC implementation.
> Isolate Crypto

- .travis.yml
Keychain tests are currently failing on iOS 10, so the Travis tests for this PR are failing. A future PR will fix the keychain issues revealed by the added tests.
> Update Travis Configuration for iOS 9.3 and 10.0

- Tests/KeychainTests.swift
Keychain access seems to be broken (error -34018) as of Xcode 8 beta 2.
https://forums.developer.apple.com/thread/51071
The current workaround for this issue is to enable the keychain sharing entitlement, but since entitlements appear to not affect test bundles, there isn't a fix for broken keychain tests. Until a future beta fixes the issue, keychain tests are disabled for iOS 10.
> Disable broken keychain tests on iOS 10 beta

- .travis.yml
- Tests/KeychainTests.swift
Merge the keychain test workaround from `master` and update the Travis config to build with Xcode 8 only.
> Swift 3 Test Fixes

- Sources/Generator.swift
- Sources/Keychain.swift
- Sources/Token+URL.swift
- Sources/Token.swift
- Tests/TokenSerializationTests.swift
Add spaces between parameter names and arguments and remove extra newlines at the beginning of types.
> Whitespace

- OneTimePassword.xcodeproj/project.pbxproj
When running `carthage update` on this project from a swift 2.3/3.0 project (xcode 8), I was getting errors about setting the `Use legacy swift version` setting. It was properly set here, but updating these few settings seems to get it building `¯\_(ツ)_/¯ `
> Updating to recommended xcode 8 project settings

- Tests/KeychainTests.swift
The broken keychain tests seem to be caused by entitlements issues with iOS 10, since tests on iOS 9 still pass with Xcode 8.
> Update the note regarding keychain tests on iOS 10

- .travis.yml
Default to using Xcode 8 for Travis builds.
Testing on iOS 8.x currently times out on Travis with Xcode 8, so those tests will remain on Xcode 7.3. This is also useful for ensuring continued support for building with Swift 2.2.
> Update Travis configuration to use Xcode 8

- .codecov.yml
- .swiftlint.yml
- .travis.yml
- CHANGELOG.md
- OneTimePassword.podspec
- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePasswordLegacyTests/OTPToken.swift
- README.md
- Sources/Crypto.swift
- Sources/Generator.swift
- Sources/Info.plist
- Sources/Keychain.swift
- Sources/Token+URL.swift
- Sources/Token.swift
- Tests/KeychainTests.swift
- Tests/TokenSerializationTests.swift
Merge in the latest changes from the Swift 2.3 branch, and update the code for compatibility with the Swift 3.0 release.
Fixes #85
> Update for Swift 3

- CHANGELOG.md
- Cartfile.resolved
- OneTimePassword.xcodeproj/project.pbxproj
- OneTimePassword.xcodeproj/xcshareddata/xcschemes/OneTimePassword.xcscheme
- Update `xcconfig` files
- Delete unnecessary and duplicated build settings
- Delete empty build phases
- Configure all targets for manual provisioning and code signing
- Delete erroneous test host configurations
- Update shared Xcode scheme
> Project cleanup

- Sources/Generator.swift
- Sources/Token+URL.swift
Clean up some of the converted Swift 3 code.
> Clean up converted Swift 3

- OneTimePassword.podspec
- OneTimePassword.xcodeproj/project.pbxproj
- Add a dependency target to all framework targets which injects the Xcode path
- Add a comment explaining the limitations of the pod's `prepare_command`
> Improve Xcode path injection

- CHANGELOG.md
- CONTRIBUTING.md
- OneTimePassword.xcodeproj/project.pbxproj
Improve the "Getting Started" instructions and add project-wide indentation configuration to the Xcode project.
> Easier new clones

- OneTimePasswordLegacyTests/OTPTokenSerializationTests.m
- Sources/Token+URL.swift
- Tests/GeneratorTests.swift
Add several tests which cover validation failures when generating a password and parsing failures when constructing a Token from a URL.
Also, fix a bug revealed by the tests, where parsing a URL with a non-integral counter parameter would return a token with an incorrect counter value.
> Add tests for validation and parsing failures

- Sources/Generator.swift
- Sources/Keychain.swift
- Sources/Token.swift
- Fix the parameter name in a `Keychain` doc comment
- Expand the doc comment for the helper method `paddedWithCharacter(_:toLength:)`
- Add a full stop at the end of each documentation comment
> Improve documentation comments

- Tests/KeychainTests.swift
Simplify the nesting of do-catch blocks in the `Keychain` tests.
> Clean up Keychain tests

- CHANGELOG.md
- CommonCrypto/injectXcodePath.sh
- Tests/KeychainTests.swift
- Add the 2.1 release date to the changeling
- Add debug logging to the Xcode path injection script (this was useful debugging an issue with `pod spec lint`)
- Fix the copyright year in KeychainTests.swift
> 2.1 pre-release changes

- .hound.yml
- .swiftlint.yml
- Sources/Token+URL.swift
- Tests/EquatableTests.swift
- Tests/TokenSerializationTests.swift
- Limit line length to 120 characters
- Enforce consistent file header comments
- Re-enable closure parameter lint rules
> Update SwiftLint configuration

- OneTimePasswordLegacyTests/OTPToken.swift
- Sources/Crypto.swift
- Sources/Keychain.swift
- Tests/KeychainTests.swift
Assorted changes from a review of the Swift 3 update:
- Use a constant `String.Encoding` for keychain conversion of token URLs
- Use Data's `withUnsafeBytes` instead of casting to `NSData`
- Use the Base32 API directly to avoid creating and then bridging `NSData`
- Update the `OTPToken` shim with Swift 3 API conventions
> Swift 3 code review

- OneTimePasswordLegacyTests/OTPToken.swift
- OneTimePasswordLegacyTests/OTPTokenTests.swift
- Sources/Crypto.swift
- Sources/Generator.swift
- Sources/Token+URL.swift
- Tests/EquatableTests.swift
- Tests/GeneratorTests.swift
- Tests/KeychainTests.swift
- Tests/TokenSerializationTests.swift
- Tests/TokenTests.swift
While not made explicitly clear in the API design guidelines, in the Foundation Swift 3 API even names with are acronyms are lower-camel-case.
https://swift.org/documentation/api-design-guidelines/#follow-case-conventions
> Convert Algorithm case names to lowercase, following Swift 3 conventions

- Sources/Generator.swift
- Sources/Token.swift
- Tests/GeneratorTests.swift
- Tests/TokenTests.swift
The user of OneTimePassword is more likely to already have a `Date` than they are to have a `TimeInterval` since the Unix epoch. An API using a `Date` is more clear, since using a `TimeInterval` requires knowledge of the base date from which the time interval is measured.
> Convert password(at:) to take a Date instead of a TimeInterval

- README.md
Update badges in the README, and change links to files in the repo to use relative paths (instead of statically referencing the defunct `master` branch).
> Update README badges and links

- .travis.yml
Use the `build-for-testing` and `test-without-building` actions as a workaround for Travis flakiness due to xcodebuild test timeouts: https://github.com/travis-ci/travis-ci/issues/6422#issuecomment-262802695
> Work around Travis test timeouts

- Sources/Keychain.swift
- Remove an optional whose only purpose was support for Xcode 7
- Explicitly clarify which `PersistentToken.init` is used by the keychain
> Assorted Keychain cleanup

- README.md
Also, add a note informing the user of the need to import the Base32 library.
> Fix the Base32-decoding function in the token creation example code

- .swiftlint.yml
- Sources/Token+URL.swift
- Tests/EquatableTests.swift
- Tests/TokenSerializationTests.swift
- Tests/TokenTests.swift
- Remove several outdated SwiftLint rules and add many new opt-in rules.
- Allow function declarations to exceed the normal line length limit.
- Include error messages in all calls to `XCTFail()`.
> SwiftLint 0.22

- OneTimePasswordLegacyTests/OTPTokenSerializationTests.m
- Sources/Token+URL.swift
- Tests/TokenSerializationTests.swift
Refactor the parsing of URL into Token, replacing the complex generic parsing helper with dedicated throwing helper methods and an overall more functional, decomposed structure. Also, improve testing of several parsing edge cases.
> Refactor token URL parsing

- Cartfile
- Cartfile.resolved
Upgrade Base32 to an intermediate version configured for Xcode 9
> Upgrade Base32

- Cartfile
- Cartfile.resolved
Update the Cartfile to depend on a tagged version of Base32, rather than a specific commit hash.
> More reliable Base32 dependency version

- .codecov.yml
Configure CodeCov to use `develop` as the default branch, and clean up the `ignore` list.
> CodeCov Configuration

- .codecov.yml
- Sources/Keychain.swift
- Sources/Token+URL.swift
- Tests/KeychainTests.swift
Add an internal throwing initializer for creating a Token from a url, and convert the failable initializer for creating a PersistentToken from a keychain dictionary to a throwing initializer.
This fixes an issue in `persistentToken(withIdentifier:)` and `allPersistentTokens()` where deserialization errors would be ignored, causing a persistent token that existed but could not be deserialized to be treated the same as a persistent token that did not exist.
> Keychain Deserialization Errors
